#!/bin/sh /etc/rc.common

# Start in RC.local for now START=96
STOP=01

USE_PROCD=1
PROG=logwifiids.py
SQLITEDB="/mnt/usb/"
NAME=wifilogger
PIDCOUNT=0


start_service()
{
	/etc/init.d/gpsd start
	sleep 1
	/etc/init.d/ntpd start
	sleep 1
	start-stop-daemon -S -b -x ${PROG} -- -d ${SQLITEDB}
}

stop_service()
{
	killall -2 ${PROG}
}
